#!/bin/bash
set -eu

LOG_FILE=/tmp/.deploy.log
CONF=/etc/deploy/
DEPLOY=/srv/deploy/

SERVER=
SECRET_KEY=M4UG6UBSA4AUHTDIAKNVZSYUE7WC6P4E2MD37ISIFLCLHVZ5B3ZFL6NQZILLRP7R3EOAVYFZAUKE
HOSTID=$(hostid)

function send() {
	TAG=$1
	URL=http://$SERVER/metrics/$SECRET_KEY/$HOSTID/$TAG
	curl -X POST --data-binary @- -H 'Content-Type: text/plain'  "$URL"
}

function send_logs() {
	cat $CONF/version |send version
	ip a |send ip
	docker ps |send docker-ps
}

function deploy() {
	VERSION_URL=http://$SERVER/deploy/$SECRET_KEY/latest_version
	DEPLOY_URL=http://$SERVER/deploy/$SECRET_KEY/deploy.tar.gz

	if ! cmp <(curl $VERSION_URL) $CONF/version; then
		# 最新版では無いことが確認できたので、デプロイスクリプトを実行
		rm -rf $DEPLOY
		curl $DEPLOY_URL >$DEPLOY.tar.gz
		mkdir -p $DEPLOY
		tar xf $DEPLOY.tar.gz -C $DEPLOY
		pushd $DEPLOY
		./deploy.sh
		popd
	fi
}

"$@" &>$LOG_FILE || send error <$LOG_FILE
rm $LOG_FILE
